import Footer from "@/components/Footer";
import "./globals.css";
import Navbar from "@/components/navbar";
import { CartProvider } from "@/Context/CartContext";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <CartProvider>
        <Navbar></Navbar>
        {children}
        <Footer></Footer>
        </CartProvider>
      </body>
    </html>
  );
}
