const products = [
  {
    id: 1,
    title: "Basic Wireless Headphones",
    price: 999,
    description: "Affordable wireless headphones with decent sound.",
    category: "Electronics",
    reviews: 4.0,
    image: "/images/img1.png",
    brand: "Samsung",
  },
  {
    id: 2,
    title: "Cotton T-Shirt",
    price: 799,
    description: "Comfortable cotton t-shirt in multiple colors.",
    category: "Clothing",
    reviews: 4.0,
    image: "/images/img2.png",
    brand: "Nike",
  },
  {
    id: 3,
    title: "Small Coffee Table",
    price: 899,
    description: "Compact wooden coffee table for small spaces.",
    category: "Home",
    reviews: 4.1,
    image: "/images/img3.png",
    brand: "LG",
  },
  {
    id: 4,
    title: "Mini Bluetooth Speaker",
    price: 999,
    description: "Portable speaker with decent bass.",
    category: "Electronics",
    reviews: 4.3,
    image: "/images/img1.png",
    brand: "Puma",
  },
  {
    id: 5,
    title: "Winter Scarf",
    price: 699,
    description: "Warm woolen scarf for cold weather.",
    category: "Clothing",
    reviews: 4.2,
    image: "/images/img2.png",
    brand: "Samsung",
  },
  {
    id: 6,
    title: "LED Desk Lamp",
    price: 899,
    description: "Adjustable desk lamp with USB charging.",
    category: "Home",
    reviews: 4.0,
    image: "/images/img3.png",
    brand: "Nike",
  },
  {
    id: 7,
    title: "Wireless Mouse",
    price: 799,
    description: "Ergonomic wireless mouse with long battery life.",
    category: "Electronics",
    reviews: 4.2,
    image: "/images/img1.png",
    brand: "LG",
  },
  {
    id: 8,
    title: "Running Socks",
    price: 499,
    description: "Breathable running socks for sports.",
    category: "Clothing",
    reviews: 4.4,
    image: "/images/img2.png",
    brand: "Puma",
  },
  {
    id: 9,
    title: "Decorative Vase",
    price: 899,
    description: "Ceramic decorative vase for home decor.",
    category: "Home",
    reviews: 3.9,
    image: "/images/img3.png",
    brand: "Samsung",
  },
  {
    id: 10,
    title: "Leather Wallet",
    price: 999,
    description: "Compact leather wallet with multiple compartments.",
    category: "Clothing",
    reviews: 4.1,
    image: "/images/img2.png",
    brand: "Nike",
  },
];

export default products;
